# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dstahlke/git/gnuplot-iostream

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dstahlke/git/gnuplot-iostream

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dstahlke/git/gnuplot-iostream/CMakeFiles /home/dstahlke/git/gnuplot-iostream/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dstahlke/git/gnuplot-iostream/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named example-interactive

# Build rule for target.
example-interactive: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example-interactive
.PHONY : example-interactive

# fast build rule for target.
example-interactive/fast:
	$(MAKE) -f CMakeFiles/example-interactive.dir/build.make CMakeFiles/example-interactive.dir/build
.PHONY : example-interactive/fast

#=============================================================================
# Target rules for targets named example-make-png

# Build rule for target.
example-make-png: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example-make-png
.PHONY : example-make-png

# fast build rule for target.
example-make-png/fast:
	$(MAKE) -f CMakeFiles/example-make-png.dir/build.make CMakeFiles/example-make-png.dir/build
.PHONY : example-make-png/fast

#=============================================================================
# Target rules for targets named example-popup

# Build rule for target.
example-popup: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example-popup
.PHONY : example-popup

# fast build rule for target.
example-popup/fast:
	$(MAKE) -f CMakeFiles/example-popup.dir/build.make CMakeFiles/example-popup.dir/build
.PHONY : example-popup/fast

#=============================================================================
# Target rules for targets named example-vectors

# Build rule for target.
example-vectors: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example-vectors
.PHONY : example-vectors

# fast build rule for target.
example-vectors/fast:
	$(MAKE) -f CMakeFiles/example-vectors.dir/build.make CMakeFiles/example-vectors.dir/build
.PHONY : example-vectors/fast

example-interactive.o: example-interactive.cc.o
.PHONY : example-interactive.o

# target to build an object file
example-interactive.cc.o:
	$(MAKE) -f CMakeFiles/example-interactive.dir/build.make CMakeFiles/example-interactive.dir/example-interactive.cc.o
.PHONY : example-interactive.cc.o

example-interactive.i: example-interactive.cc.i
.PHONY : example-interactive.i

# target to preprocess a source file
example-interactive.cc.i:
	$(MAKE) -f CMakeFiles/example-interactive.dir/build.make CMakeFiles/example-interactive.dir/example-interactive.cc.i
.PHONY : example-interactive.cc.i

example-interactive.s: example-interactive.cc.s
.PHONY : example-interactive.s

# target to generate assembly for a file
example-interactive.cc.s:
	$(MAKE) -f CMakeFiles/example-interactive.dir/build.make CMakeFiles/example-interactive.dir/example-interactive.cc.s
.PHONY : example-interactive.cc.s

example-make-png.o: example-make-png.cc.o
.PHONY : example-make-png.o

# target to build an object file
example-make-png.cc.o:
	$(MAKE) -f CMakeFiles/example-make-png.dir/build.make CMakeFiles/example-make-png.dir/example-make-png.cc.o
.PHONY : example-make-png.cc.o

example-make-png.i: example-make-png.cc.i
.PHONY : example-make-png.i

# target to preprocess a source file
example-make-png.cc.i:
	$(MAKE) -f CMakeFiles/example-make-png.dir/build.make CMakeFiles/example-make-png.dir/example-make-png.cc.i
.PHONY : example-make-png.cc.i

example-make-png.s: example-make-png.cc.s
.PHONY : example-make-png.s

# target to generate assembly for a file
example-make-png.cc.s:
	$(MAKE) -f CMakeFiles/example-make-png.dir/build.make CMakeFiles/example-make-png.dir/example-make-png.cc.s
.PHONY : example-make-png.cc.s

example-popup.o: example-popup.cc.o
.PHONY : example-popup.o

# target to build an object file
example-popup.cc.o:
	$(MAKE) -f CMakeFiles/example-popup.dir/build.make CMakeFiles/example-popup.dir/example-popup.cc.o
.PHONY : example-popup.cc.o

example-popup.i: example-popup.cc.i
.PHONY : example-popup.i

# target to preprocess a source file
example-popup.cc.i:
	$(MAKE) -f CMakeFiles/example-popup.dir/build.make CMakeFiles/example-popup.dir/example-popup.cc.i
.PHONY : example-popup.cc.i

example-popup.s: example-popup.cc.s
.PHONY : example-popup.s

# target to generate assembly for a file
example-popup.cc.s:
	$(MAKE) -f CMakeFiles/example-popup.dir/build.make CMakeFiles/example-popup.dir/example-popup.cc.s
.PHONY : example-popup.cc.s

example-vectors.o: example-vectors.cc.o
.PHONY : example-vectors.o

# target to build an object file
example-vectors.cc.o:
	$(MAKE) -f CMakeFiles/example-vectors.dir/build.make CMakeFiles/example-vectors.dir/example-vectors.cc.o
.PHONY : example-vectors.cc.o

example-vectors.i: example-vectors.cc.i
.PHONY : example-vectors.i

# target to preprocess a source file
example-vectors.cc.i:
	$(MAKE) -f CMakeFiles/example-vectors.dir/build.make CMakeFiles/example-vectors.dir/example-vectors.cc.i
.PHONY : example-vectors.cc.i

example-vectors.s: example-vectors.cc.s
.PHONY : example-vectors.s

# target to generate assembly for a file
example-vectors.cc.s:
	$(MAKE) -f CMakeFiles/example-vectors.dir/build.make CMakeFiles/example-vectors.dir/example-vectors.cc.s
.PHONY : example-vectors.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... example-interactive"
	@echo "... example-make-png"
	@echo "... example-popup"
	@echo "... example-vectors"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... example-interactive.o"
	@echo "... example-interactive.i"
	@echo "... example-interactive.s"
	@echo "... example-make-png.o"
	@echo "... example-make-png.i"
	@echo "... example-make-png.s"
	@echo "... example-popup.o"
	@echo "... example-popup.i"
	@echo "... example-popup.s"
	@echo "... example-vectors.o"
	@echo "... example-vectors.i"
	@echo "... example-vectors.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

